name: 🚀 CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t myproject:latest .
          docker tag myproject:latest ${{ secrets.DOCKER_USERNAME }}/myproject:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOT_ENV_FILE }}" > .env
            docker pull ${{ secrets.DOCKER_USERNAME }}/myproject:latest
            docker stop myproject || true
            docker rm myproject || true
            docker run -d --name myproject --env-file .env -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myproject:latest
